
spring.application.name=witcher-toolkit-back
server.servlet.context-path=/witcher-toolkit
server.port=8081

# ------------------ CONFIGURATION BDD MARIA-DB ----------------------- #
spring.datasource.url=jdbc:mariadb://localhost:3306/witchertoolkit
spring.datasource.username=root
#spring.datasource.password=mon_mot_de_passe
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate DDL : cr\u00E9er ou mettre \u00E0 jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Debug SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ------------------ CONFIGURATION BDD MARIA-DB ----------------------- #
# ---------------------------- MYBATIS -------------------------------- #

# Chemin des entit\u00E9s (domaines)
mybatis.type-aliases-package=fr.meya.witcher.model

# Init script SQL (optionnel si tu veux garder schema.sql / data.sql)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema/schema.sql
spring.sql.init.data-locations=classpath:schema/data.sql

# (facultatif) Formatage SQL dans les logs
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# ---------------------------- MYBATIS -------------------------------- #