
spring.application.name=witcher-toolkit-back
server.servlet.context-path=/witcher-toolkit
server.port=8081

# ------------------CONFIGURATION BDD MARIA-DB ----------------------- #
spring.datasource.url=jdbc:mariadb://localhost:3306/witchertoolkit
spring.datasource.username=root
#spring.datasource.password=mon_mot_de_passe
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate DDL : créer ou mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Debug SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ------------------CONFIGURATION BDD MARIA-DB ----------------------- #