
-- Ajout des Caractéristiques
INSERT INTO caracteristique (id_caracteristique, nom, code, description) VALUES
    (1, 'Intelligence', 'INT', 'Permet de résoudre des énigmes, de réaliser des expériences scientifiques, de construire des raisonnements logiques…'),
    (2, 'Réflexes', 'RÉF', 'Sert à combattre, esquiver et effectuer des actions nécessitant des réactions rapides et des gestes précis.'),
    (3, 'Dextérité', 'DEX', 'Pour les attaques à distance et tout ce qui implique de faire appel à l''équilibre et à la coordination œil-main.'),
    (4, 'Corps', 'COR', 'S''utilise lorsqu''il faut faire appel à la force brute, comme pour les bagarres ou les prouesses physiques. Le corps représente aussi l''endurance nécessaire pour résister aux maladies ou à la fatigue.'),
    (5, 'Vitesse', 'VIT', 'Représente la vitesse de déplacement de votre personnage. Vous pouvez utiliser cette caractéristique pour semer les poursuivants ou calculer la distance parcourue dans un temps donné.'),
    (6, 'Empathie', 'EMP', 'Pour gérer les affaires de cœur et les émotions. La séduction et la persuasion font appel à cette caractéristique.'),
    (7, 'Technique', 'TECH', 'Pour utiliser des mécanismes ou créer des objets avec précision. La technique sert également à manier des machines de siège et à installer des pièges.'),
    (8, 'Volonté', 'VOL', 'Sert à intimider, mais aussi à réaliser des tests magiques et de résistance mentale. La volonté dénote votre capacité à aller de l''avant et votre degré de maîtrise de la magie.'),
    (9, 'Chance', 'CHA', 'La chance est une réserve de points que vous pouvez utiliser pour retourner les situations à votre avantage. Avant d''effectuer un jet de compétence (ou un jet de sauvegarde contre la mort), pendant votre tour ou en défense pendant le tour d''un adversaire, vous pouvez ajouter des points de chance. Vous bénéficiez de +1 par point ajouté, sachant que vous devez décider du montant dépensé avant de lancer les dés. Votre réserve de chance se reconstitue au début de chaque session de jeu.'),
    (10, 'Vigueur', 'VIG', 'Votre valeur de Vigueur correspond au nombre de points de Chaos que vous pouvez canaliser sans vous blesser. Vous subissez des dégâts lorsque le coût d''endurance de tous les sorts que vous lancez pendant un round est supérieur à cette valeur.'),
    (11, 'Étourdissement', 'ÉTOU', 'Pour savoir à quel point votre personnage peut résister aux coups avant de finir étourdi ou inconscient, il faut se reporter à sa valeur d''étourdissement. Lorsque vous devez effectuer un jet de sauvegarde d''étourdissement, vous devez obtenir un résultat inférieur à cette caractéristique ou être étourdi.'),
    (12, 'Course', 'VIT', 'Cette valeur correspond à votre vitesse quand vous courez à une allure raisonnable. En un tour, vous pouvez parcourir un nombre de mètres égal à votre valeur de course.'),
    (13, 'Saut', 'SAU', 'La valeur de Saut correspond au nombre de mètres que vous parcourez en sautant après avoir pris de l''élan.'),
    (14, 'Points de santé', 'PS', 'La santé correspond au nombre de points de dégâts que vous pouvez subir avant de passer en état de mort imminente et de succomber à une hémorragie.'),
    (15, 'Endurance', 'END', 'L''endurance représente l''énergie que vous pouvez dépenser lors d''un effort physique ou d''un acte magique avant de finir épuisé (elle représente également la difficulté à vous mettre K.O.). Lorsque vous n''avez plus de points d''endurance, vous êtes étourdi et vous ne pouvez rien faire à part vous remettre. Lorsque vous n’en avez plus, vous devenez épuisé et ne pouvez plus rien faire à part récupérer. Lorsque vous lancez un sort, que vous effectuez des actions supplémentaires en combat, que vous utilisez certaines capacités ou que vous subissez des dégâts non létaux, vous piochez aussi dans votre réserve d''endurance. En général, 1 minute d’effort intense ou 1 heure de travail répétitif fait perdre 2 points d''endurance. Quand vous effectuez une action Récupérer, vous regagnez un nombre de points d''endurance égal à votre valeur de récupération.'),
    (16, 'Encombrement', 'ENC', 'Cette valeur reflète le poids que vous pouvez porter sans être ralentis. Dès que vous êtes encombré, vous diminuez de -1 vos valeurs de RÉF, DEX et VIT pour chaque tranche de 5 points au-dessus de votre valeur d''encombrement, avec un minimum de 1. Vous pouvez soulever au maximum 50 fois votre valeur de corps en kilogrammes.'),
    (17, 'Récupération', 'RÉC', 'La récupération indique le nombre de points de santé que vous regagnez par jour de repos au calme dans un lit. Pour retrouver ces points de santé, quelqu’un doit d''abord réussir un jet de premiers soins ou de mains thérapeutiques sur vous.'),
    (18, 'Pieds', 'Pieds', 'Cette caractéristique indique le nombre de dégâts non létaux que vous infligez avec un coup de poing.'),
    (19, 'Poings', 'Poings', 'Cette caractéristique indique le nombre de dégâts non létaux que vous infligez avec un coup de pied.');

-- ALTER TABLE caracteristique ALTER COLUMN id_caracteristique RESTART WITH 20;

-- Ajout de Compétences
INSERT INTO competence (id_competence, nom, description, exclusive, specialisation, prerequis, id_caracteristique) VALUES
    (1, 'Connaissance de la rue', 'Cette compétence ne concerne pas la géographie urbaine à proprement parler, mais plutôt le fonctionnement de cet environnement. Avec une base de 10 vous en savez suffisamment pour éviter les voyous et vous rendre dans les quartiers les plus sûrs de la ville. Avec une base de 13 vous pouvez en général déterminer quelle faction exerce son influence sur un quartier donné et expliquer la raison de cette domination. Avec une base de 16 vous pouvez récolter une quantité d’informations impressionnantes sur une zone rien qu’en l’observant, mais aussi identifier les personnalités importantes de la ville et leurs relations. Avec une base de 20 vous évaluez la situation en un clin d’œil. Vous en savez assez pour compter parmi les habitants.', '', '', false, 1 ),
    (2, 'Connaissance des monstres', 'La somme d’information que vous possédez à propos des monstres. Avec une base de 10 vous êtes capable de différencier un nekker d’une goule. Avec une base de 13 vous savez classer les monstres au sein des diverses catégories générales. Avec une base de 16 vous êtes au fait des différentes forces et faiblesses que possèdent les créatures les plus communes. Avec une base de 20 il est rare que vous rencontriez des monstres que vous seriez incapable d’analyser en quelques secondes, un exploit dont même un sorceleur serait fier.','Criminel', 'N/A', false, 1),
    (3, 'Déduction', 'La capacité à formuler des conclusions grâce aux indices dont vous disposez. Avec une base de 10 vos intuitions vous mettent en général sur la bonne piste. Avec une base de 13 vos ressentiments sont presque toujours fondés, vous pouvez même les étayer à l’aide de raisonnements logiques. Avec une base de 16 il vous suffit de quelques indices pour avoir ce qui s’est passé ou ce qui pourrait advenir. Avec une base de 20 vous ne vous trompez presque jamais dans vos déductions. Vous êtes capables de trouver des réponses même lorsque vous disposez de preuves partielles.','Criminel', 'Connaissance', false, 1 ),
    (4, 'Éducation', 'Reflète votre niveau d’instruction. Avec une base de 10 vos parents vous ont légué des connaissances sommaires sur la marche du monde. Avec une base de 13 vous avez probablement bénéficié des leçons d’un mentor ou eu la chance de fréquenter l’une des rares écoles ouvertes dans votre région natale. Avec une base de 16 vous avez acquis un savoir encyclopédique en allant par exemple étudier à Oxenfurt ou dans une autre académie du genre. Avec une base de 20 vous êtes un érudit capable de rivaliser d’intelligence avec des professeurs d’université et des mages siégeant aux conseils royaux.','', '', false, 1),
    (5, 'Enseignement', 'La capacité à dispenser son savoir. Vous n’êtes pas tenu de maîtriser cette capacité pour en enseigner d’autres, mais elle vous facilitera la tâche. Avec une base de 10 vous savez expliquer du début à la fin un procédé simple à votre élève, mais sans que ce dernier saisisse à coup sûr tous les tenants et aboutissants de votre cheminement. Avec une base de 13 vVous pouvez enseigner les bases d’une compétence à un élève attentif sans rencontrer de problème particulier. Avec une base de 16 si vous disposez de suffisamment de temps, vous pouvez apprendre des procédés plus complexes à vos étudiants, même s’ils ne sont guère attentifs. Avec une base de 20 vous êtes un maître pédagogue capable d’intéresser n’importe qui. Puisque vos leçons font toujours mouche du premier coup, vous avez rarement besoin de vous répéter.', '', '', false, 1 ),
	(6, 'Étiquette',  'La capacité à dispenser son savoir. Vous n’êtes pas tenu de maîtriser cette capacité pour en enseigner d’autres, mais elle vous facilitera la tâche. Avec une base de 10 vous savez expliquer du début à la fin un procédé simple à votre élève, mais sans que ce dernier saisisse à coup sûr tous les tenants et aboutissants de votre cheminement. Avec une base de 13 vous pouvez enseigner les bases d’une compétence à un élève attentif sans rencontrer de problème particulier. Avec une base de 16 si vous disposez de suffisamment de temps, vous pouvez apprendre des procédés plus complexes à vos étudiants, même s’ils ne sont guère attentifs. Avec une base de 20 vous êtes un maître pédagogue capable d’intéresser n’importe qui. Puisque vos leçons font toujours mouche du premier coup, vous avez rarement besoin de vous répéter.', '', '', false, 1 ),
	(7, 'Langue', 'La capacité à dispenser son savoir. Vous n’êtes pas tenu de maîtriser cette capacité pour en enseigner d’autres, mais elle vous facilitera la tâche. Avec une base de 10 vous savez expliquer du début à la fin un procédé simple à votre élève, mais sans que ce dernier saisisse à coup sûr tous les tenants et aboutissants de votre cheminement. Avec une base de 13 vous pouvez enseigner les bases d’une compétence à un élève attentif sans rencontrer de problème particulier. Avec une base de 16 si vous disposez de suffisamment de temps, vous pouvez apprendre des procédés plus complexes à vos étudiants, même s’ils ne sont guère attentifs. Avec une base de 20 vous êtes un maître pédagogue capable d’intéresser n’importe qui. Puisque vos leçons font toujours mouche du premier coup, vous avez rarement besoin de vous répéter.', '', '', false, 1 ),
	(8, 'Négoce', 'La capacité à dispenser son savoir. Vous n’êtes pas tenu de maîtriser cette capacité pour en enseigner d’autres, mais elle vous facilitera la tâche. Avec une base de 10 vous savez expliquer du début à la fin un procédé simple à votre élève, mais sans que ce dernier saisisse à coup sûr tous les tenants et aboutissants de votre cheminement. Avec une base de 13 vous pouvez enseigner les bases d’une compétence à un élève attentif sans rencontrer de problème particulier. Avec une base de 16 si vous disposez de suffisamment de temps, vous pouvez apprendre des procédés plus complexes à vos étudiants, même s’ils ne sont guère attentifs. Avec une base de 20 vous êtes un maître pédagogue capable d’intéresser n’importe qui. Puisque vos leçons font toujours mouche du premier coup, vous avez rarement besoin de vous répéter.' , '', '', false, 2),
	(9, 'Survie', 'La capacité à dispenser son savoir. Vous n’êtes pas tenu de maîtriser cette capacité pour en enseigner d’autres, mais elle vous facilitera la tâche. Avec une base de 10 vous savez expliquer du début à la fin un procédé simple à votre élève, mais sans que ce dernier saisisse à coup sûr tous les tenants et aboutissants de votre cheminement. Avec une base de 13 vous pouvez enseigner les bases d’une compétence à un élève attentif sans rencontrer de problème particulier. Avec une base de 16 si vous disposez de suffisamment de temps, vous pouvez apprendre des procédés plus complexes à vos étudiants, même s’ils ne sont guère attentifs. Avec une base de 20 vous êtes un maître pédagogue capable d’intéresser n’importe qui. Puisque vos leçons font toujours mouche du premier coup, vous avez rarement besoin de vous répéter.' , '', '', false, 2),
	(10, 'Tactique', 'La capacité à dispenser son savoir. Vous n’êtes pas tenu de maîtriser cette capacité pour en enseigner d’autres, mais elle vous facilitera la tâche. Avec une base de 10 vous savez expliquer du début à la fin un procédé simple à votre élève, mais sans que ce dernier saisisse à coup sûr tous les tenants et aboutissants de votre cheminement. Avec une base de 13 vous pouvez enseigner les bases d’une compétence à un élève attentif sans rencontrer de problème particulier. Avec une base de 16 si vous disposez de suffisamment de temps, vous pouvez apprendre des procédés plus complexes à vos étudiants, même s’ils ne sont guère attentifs. Avec une base de 20 vous êtes un maître pédagogue capable d’intéresser n’importe qui. Puisque vos leçons font toujours mouche du premier coup, vous avez rarement besoin de vous répéter.' , '', '', false, 2);

-- ALTER TABLE competence ALTER COLUMN id_competence RESTART WITH 11;

-- Ajout de Professions
INSERT INTO profession (id_profession, nom, description, vigueur, nb_objet, max_sort, max_rituel, max_envoutement, max_invocation) VALUES
    (1, 'Artisan', 'Un artisan talentueux peut effectuer des réparations de fortune sur une armure ou une arme pour qu’elle reste utilisable le temps du combat. Il pourra par exemple nouer deux parties d’une corde d’arc rompue, affûter la lame d’une épée ou clouer une plaque de métal sur un bouclier fendu. L’artisan consacre un tour à cette action. Il effectue alors un jet de rafistolage dont le SD est égal au SD de fabrication de l’objet -3. S’il réussit, l’armure brisée regagne la moitié de son PA total, ou la moitié de sa fiabilité dans le cas d’une épée ou d’un bouclier. Tant qu’elle n’est pas correctement réparée à l’aide d’une forge, une arme n’inflige que la moitié des dégâts normaux.', 0, 0, 0, 0, 0, 0),
    (2, 'Barde', 'Le barde est un compagnon des plus précieux, surtout quand le groupe commence à manquer d''argent. Il peut réaliser un jet de prestation et se donner en spectacle sur la place de la ville durant une heure. Le résultat du jet correspond au montant qu’il a récolté en se produisant dans la rue. Un échec critique peut diminuer le résultat du jet, et si le total devient négatif, cela signifie que la barde n’a pas réussi à recueillir une seule pièce. Il se fait huer par les habitants pour sa piètre performance et subit un malus de -2 en charisme lorsqu’il interagit avec les citadins jusqu''à la fin de la journée.', 0, 0, 0, 0, 0, 0),
    (3, 'Criminel', 'Qu''ils soient assassins, voleurs faussaires ou contrebandiers, tous les hors-la-loi ont en commun une paranoïa constante qui leur permet d’éviter les problèmes. Lorsqu’un criminel arrive à moins de 10m d''un piège (ce qui inclut les pièges expérimentaux, les chausses-trappes des hommes d''armes et les embuscades), il effectue immédiatement un jet de paranoïa exercée dont le SD est égal à celui requis pour déceler le piège, au résultat du jet de furtivité du groupe posté en embuscade ou au SD fixé par le MJ. Même s''il n''arrive pas à repérer le piège, il sentira au fond de lui-même que quelque-chose ne va pas.', 0, 0, 0, 0, 0, 0),
    (4, 'Docteur', 'N’’importe qui est capable d’’appliquer un onguent ou de bander une blessure, mais seul un docteur a reçu la formation nécessaire pour accomplir des actes chirurgicaux d’’une grande complexité. Un docteur avec mains thérapeutiques est le seul personnage capable de soigner une blessure critique. Pour soigner une blessure critique, il doit réussir un nombre de jets de mains thérapeutiques qui dépend de la gravité de cette blessure. Le SD du jet est aussi basé sur ce paramètre. Les mains thérapeutiques peuvent aussi servir lors des actions de premiers soins.', 0, 0, 0, 0, 0, 0 ),
    (5, 'Homme d''arme', 'Les véritables hommes d’’armes issus, par exemple, des Stries Bleues témériennes ou de la brigade Imprera de Nilfgaard sont des vétérans endurcis qui n’’abandonnent jamais et ne se rendent pas. Lorsque les points de santé d’’un homme d’’armes tombent à 0 ou moins, il peut effectuer un jet de dur à cuire dont le SD est égal au double de son score de santé négatif. S’’il échoue, il entre en état de mort imminente selon les règles habituelles. S’’il le réussit, il peut continuer à se battre comme s’’il avait atteint son seuil de blessures. Lorsqu’’il subit des dégâts, il réalise un nouveau jet dont le SD est calculé selon son nouveau score de santé.', 0, 0, 0, 0, 0, 0),
    (6,'Mage','Pour devenir pleinement un mage, une personne sensible à la magie doit apprendre les bases de cet art au sein d’’une académie de magie. Un mage peut réaliser un jet d’exercice de la magie dès qu’il se trouve face à un phénomène magique ou un sort inconnu, ou encore lorsqu’il analyse une théorie de la magie. Le SD du jet est fixé par le MJ. En cas de réussite, le mage apprend tout ce qu’’il y a à savoir sur le phénomène en question. Un jet d’exercice de la magie peut aussi servir à détecter la magie en cours d’utilisation ou les spectres.', 5, 0, 5, 1, 1, 0),
    (7, 'Marchand', 'Un marchand ordinaire gagne sa vie grâce à son échope qui attire les clients alentours. En revanche, un commerçant itinérant part à la rencontre de ses clients. Il parcourt les routes du monde entier, ce qui lui permet d’’en apprendre beaucoup sur les peuples qu’’il croise. Un marchand peut effectuer un jet de grand voyageur chaque fois qu’’il désire connaître une anecdote concernant un objet, une culture ou une région particulière. Le MJ fixe le SD du jet. Si ce dernier réussit, le marchand se rappelle la réponse à la question posée grâce aux souvenirs datant de son dernier voyage dans le lieu concerné.', 0, 0, 0, 0, 0, 0),
    (8, 'Prêtre', 'Les temples du monde entier sont bien souvent des lieux chaleureux qui aident les fidèles et accueillent les nouveaux convertis. Un prêtre peut réaliser un jet d’initié des dieux dont le SD est fixé par les MJ dans les églises de cette religion pour obtenir un hébergement gratuit, des soins et d’autres services, à la discrétion du MJ. L’initiation des dieux fonctionne aussi auprès des croyants de la même confession, bien qu’ils aient moins à offrir qu’un temple. N’oubliez pas qu’initié des dieux ne fonctionne jamais avec les membres d’une autre religion.', 2, 0,0,  2, 2, 2),
    (9, 'Sorceleur', 'Les sorceleurs passent les premières années de leur vie confinés entre les murs de leur forteresse, où ils étudient d’énormes tomes poussiéreux et suivent un entraînement martial démentiel. De nombreux savants ont démontré que les meilleures armes d’un sorceleur étaient sa connaissance des monstres ainsi que ses capacités d’’adaptation. Il peut donc diminuer les pénalités provoquées par un environnement hostile ou un relief accidenté d’’une valeur égale à la moitié de son score de formation de sorceleur (minimum 1). Vous pouvez également utiliser formation de sorceleur dans les situations requérant l’’usage de la compétence connaissance des monstres.', 2, 0, 0, 0, 0, 0),
    (10, 'Noble', 'Qu’’il soit noble de naissance ou qu’’il ait acquis ses titres en accomplissant des faits d’’armes, l’’aristocrate affiche son statut privilégié afin que nul ne l’ignore. Les paysans peuvent bien maudire les familles nobles et les ridiculiser à l’abri dans leurs chaumières, mais aucun d’’entre eux n’’oserait les insulter en face. Un noble ajoute son niveau de prestige à son score de réputation lorsqu’’il se trouve sur sa terre natale ou dans un pays allié. Lorsqu’’il se rend dans un territoire ouvertement en guerre avec son pays d’’origine ou qui conserve une position de neutralité, il n’’ajoute que la moitié de son niveau de prestige.', 0, 0, 0, 0, 0, 0);

-- ALTER TABLE profession ALTER COLUMN idProfession RESTART WITH 11;

-- Ajout de l'inventaire wiki
INSERT INTO inventaire_wiki (id_inventaire_wiki, quantite, nom, type, effet, is_special, id_profession) VALUES
    ( 1, '50', 'couronnes de composants', '', '', FALSE, 1),
    ( 2, '1', 'ensemble d''alchimie', '', '', FALSE, 1),
    ( 3, '1', 'épée longue de fer', 'arme', '', FALSE, 1),
    ( 4, '1', 'forge portable', '', '', FALSE, 1),
    ( 5, '1', 'masse d''armes', 'arme', '', FALSE, 1),
    ( 6, '1', 'outils d''artisan', '', '', FALSE, 1),
    ( 7, '1', 'outils de marchand', '', '', FALSE, 1),
    ( 8, '1', 'petit coffre', '', '', FALSE, 1),
    ( 9, '1', 'sablier', '', '', FALSE, 1),
    ( 10, '1', 'serrure', '', '', FALSE, 1),
    ( 11, '1', 'bourse', '', '', FALSE, 2),
    ( 12, '1', 'dague', 'arme', '', FALSE, 2),
    ( 13, '1', 'flasque d''alcool', '', '', FALSE, 2),
    ( 14, '1', 'fourreau de jarretière', '', '', FALSE, 2),
    ( 15, '1', 'jeu de qwynt', '', '', FALSE, 2),
    ( 16, '1', 'journal cadenassé', '', '', FALSE, 2),
    ( 17, '1', 'miroir de poche', '', '', FALSE, 2),
    ( 18, '1', 'parfum/eau de toilette', '', '', FALSE, 2),
    ( 19, '1', 'piste de dé', '', '', FALSE, 2),
    ( 20, '1', 'un instrument', '', '', FALSE, 2),
    ( 21, '1', 'chloroforme', '', '', FALSE, 3),
    ( 22, '1', 'coup-de-poind', '', '', FALSE, 3),
    ( 23, '5', 'coureaux de lancer', 'arme', '', FALSE, 3),
    ( 24, '1', 'dés pipés', '', '', FALSE, 3),
    ( 25, '1', 'fourreaux de manche', '', '', FALSE, 3),
    ( 26, '1', 'lanterne sourde', '', '', FALSE, 3),
    ( 27, '1', 'outils de voleur', '', '', FALSE, 3),
    ( 28, '1', 'sacoche', '', '', FALSE, 3),
    ( 29, '1', 'stylet', 'arme', '', FALSE, 3),
    ( 31, '10', 'bougies', '', '', FALSE, 4),
    ( 32, '1', 'couverture', '', '', FALSE, 4),
    ( 33, '1', 'dague', 'arme', '', FALSE, 4),
    ( 34, '10', 'fluide de sterilisation', '', '', FALSE, 4),
    ( 35, '1', 'grande tente', '', '', FALSE, 4),
    ( 36, '10', 'herbes engourdissantes', '', '', FALSE, 4),
    ( 37, '1', 'instruments chirurgicaux', '', '', FALSE, 4),
    ( 38, '1', 'necessaire d''écriture', '', '', FALSE, 4),
    ( 39, '10', 'poudre de coagulation', '', '', FALSE, 4),
    ( 40, '1', 'sablier', '', '', FALSE, 4),
    ( 41, '1', 'arbalète + 20 carreaux', 'arme', '', FALSE, 5),
    ( 42, '1', 'boble d''acier', 'bouclier', '', FALSE, 5),
    ( 43, '1', 'brigandine', 'armure', '', FALSE, 5),
    ( 44, '1', 'camail', '', '', FALSE, 5),
    ( 45, '5', 'couteaux de lancer', 'arme', '', FALSE, 5),
    ( 46, '1', 'hache de bataille', 'arme', '', FALSE, 5),
    ( 47, '1', 'Kord', 'arme', '', FALSE, 5),
    ( 48, '1', 'lance', 'lance', '', FALSE, 5),
    ( 49, '1', 'pantalon renforcé', 'armure', '', FALSE, 5),
    ( 50, '1', 'sacoche', '', '', FALSE, 5),
    ( 51, '100', 'couronnes de composants', '', '', FALSE, 6),
    ( 52, '1', 'bâton', 'arme', '', FALSE, 6),
    ( 53, '1', 'bourse', '', '', FALSE, 6),
    ( 54, '1', 'dague', 'arme', '', FALSE, 6),
    ( 55, '1', 'fourreau de jarretière', '', '', FALSE, 6),
    ( 56, '1', 'journal', '', '', FALSE, 6),
    ( 57, '1', 'miroir de poche', '', '', FALSE, 6),
    ( 58, '1', 'necessaire d''écriture', '', '', FALSE, 6),
    ( 59, '1', 'sablier', '', '', FALSE, 6),
    ( 60, '1', 'trousse de maquillage', '', '', FALSE, 6),
    ( 61, '1', 'arbalète + 20 carreaux', 'arme', '', FALSE, 7),
    ( 62, '1', 'dague', '', '', FALSE, 7),
    ( 63, '1', 'grande tente', '', '', FALSE, 7),
    ( 64, '1', 'journal', '', '', FALSE, 7),
    ( 65, '1', 'nécessaire d''écriture', '', '', FALSE, 7),
    ( 66, '1', 'outils de marchand', '', '', FALSE, 7),
    ( 67, '100', 'couronnes de composants', '', '', FALSE, 8),
    ( 68, '1', 'bâton', 'arme', '', FALSE, 8),
    ( 69, '1', 'dague', 'arme', '', FALSE, 8),
    ( 70, '1', 'ensemble d''alchimie', '', '', FALSE, 8),
    ( 71, '5', 'fluide stérilisant', '', '', FALSE, 8),
    ( 72, '5', 'herbes engourdissantes', '', '', FALSE, 8),
    ( 73, '1', 'instruments chirurgicaux', '', '', FALSE, 8),
    ( 74, '5', 'poudre de coagulation', '', '', FALSE, 8),
    ( 75, '1', 'sablier', '', '', FALSE, 8),
    ( 76, '1', 'symbole sacré', '', '', FALSE, 8),
    ( 77, '1', 'arbalète de poing', 'arme', '', FALSE, 9),
    ( 78, '5', 'couteaux de lancé', 'arme', '', FALSE, 9),
    ( 79, '1', 'ensemble d''alchimie', '', '', FALSE, 9),
    ( 80, '1', 'gambison à tissage rembourré', 'armure', '', FALSE, 9),
    ( 81, '1', 'cheval', '', '', FALSE, 9),
    ( 82, '1', 'épée de sorceleur en acier', '', '', TRUE, 9),
    ( 83, '1', 'épée de sorceleur en argent', '', '', TRUE, 9),
    ( 84, '1', 'formule de décoction', '', '', TRUE, 9),
    ( 85, '2', 'formule d''huile', '', '', TRUE, 9),
    ( 86, '2', 'formule de potion', '', '', TRUE, 9),
    ( 87, '1', 'médaillon de sorceleur', '', '', TRUE, 9),
    ( 88, '1', 'bijou', '', '', FALSE, 10),
    ( 89, '1', 'cheval', '', '', FALSE, 10),
    ( 90, '1', 'eau de toilette', '', '', FALSE, 10),
    ( 91, '1', 'encre invisible', '', '', FALSE, 10),
    ( 92, '1', 'esboda', 'arme', '', FALSE, 10),
    ( 93, '1', 'journal cadenassé', '', '', FALSE, 10),
    ( 94, '1', 'nécessaire d''écriture', '', '', FALSE, 10),
    ( 95, '1', 'poche secrète', '', '', FALSE, 10),
    ( 96, '1', 'trousse de maquillage', '', '', FALSE, 10),
    ( 97, '1', 'vêtements à la mode', '', '', FALSE, 10);

-- ALTER TABLE inventaireWiki ALTER COLUMN id_inventaire_wiki RESTART WITH 98;

INSERT INTO competence_profession (id_profession, id_competence) VALUES
    (1,1),
    (1,2),
    (1,3),
    (2,4),
    (2,5),
    (2,6),
    (3,7),
    (3,8),
    (3,9),
    (4,10),
    (4,1),
    (4,2),
    (5,3),
    (5,4),
    (5,5),
    (6,6),
    (6,7),
    (6,8),
    (7,9),
    (7,10),
    (7,1),
    (8,2),
    (8,3),
    (8,4),
    (9,5),
    (9,6),
    (9,7),
    (10,8),
    (10,9),
    (10,10);

-- Ajout d'envoûtement
INSERT INTO envoutement (id_envoutement, nom, cout, effet, prerequis, danger)
VALUES
    (1, 'L''envoûtement des Ombres', '4', 'L''envoûtement des ombres crée des murmures dans les ténèbres et des silhouettes dans les coins. Le sujet doit faire des jets de vigilance au hasard avec un SD non spécifié, apercevant toujours quelque chose ou quelqu''un du coin de l’œil. Les jets de vigilance ne sont jamais pour une menace réelle, juste des visions.  Le sujet doit apporter un bol d''eau pure, une branche de myrte blanc et une bouteille d''encre dans une clairière lors d’une lune croissante. Quand la lune est au plus haut, le sujet doit verser l’encre dans l’eau, tremper la branche dans le mélange et asperger des gouttelettes en cercle autour de lui tout en retenant sa respiration.', 'Un bol d''eau pure, une branche de myrte blanc, une bouteille d''encre, une clairière, une lune croissante', 'Faible'),
    (2, 'La démangeaison éternelle', '4', 'La démangeaison éternelle fait pousser des pustules qui grattent et brûlent sur les parties intimes du sujet. La démangeaison n''inflige pas de dégâts, mais dérange constamment, ce qui inflige un malus de -1 à toutes les tâches. En plus du -1, la cible a un malus de -5 en séduction une fois dans "la chambre à coucher".    Le sujet doit rassembler 1 dose de sclérodermie, de petite ciguë et de bryone. Il doit allumer un feu de camp et faire un bouquet avec les herbes. Quand tout est prêt, le sujet doit embraser les herbes et effriter les cendres chaudes sur la zone atteinte tout en récitant une série de mots magiques.', '1 dose de sclérodermie, 1 dose de petite ciguë, 1 dose de bryone, un feu de camp', 'Faible'),
    (3, 'La chance démoniaque', '8', 'La chance démoniaque tourmente le sujet avec des touches de mauvaise fortune. Dans des situations très stressantes, comme un combat ou en effectuant une tâche avec un délai très court ou un SD supérieur à 15, le sujet fait un échec critique sur un 1 ou 2 naturel.', 'Un clou en argent, 2 doses d''aconit, une mèche de cheveux d''une vierge', 'Modéré'),
    (4, 'Le cauchemar', '8', 'Le cauchemar fait revivre au sujet le même cauchemar horrifique.Chaque nuit, le sujet doit faire un jet de résistance à la contrainte avec un SD égal au jet d''envoûtement du lanceur pour lancer cet envoûtement. En cas de réussite, le sujet parvient à dormir une nuit complète, bien qu''elle ne soit pas reposante. En cas d’échec, il dort à peine et ne régénère pas d''END ou de PS durant la nuit. S’il échoue trois nuits d’affilée, il réduit de moitié son endurance et a un malus de -2 à toutes ses actions jusqu’à pouvoir faire une nuit complète.', '5 bougies, 5 os de bête, 1 minerai luisant', 'Modéré'),
    (5, 'Le baiser de Pesta', '12', 'Le baiser de Pesta ôte au sujet sa capacité de combattre les maladies et sa résistance à la nausée. À chaque fois que le sujet est en contact avec une personne malade, il a 75% de chance d’attraper la maladie. À chaque fois que il sent quelque chose de nauséabond, même légèrement, il doit réussir un jet de résilience avec un SD 16 ou être nauséeux.', '3 doses d''argile alluviale, 1 dose de charbon, 3 doses de résine, 1 dose de poussière imprégnée', 'Élevé'),
    (6, 'L''envoûtement de la bête', '12', 'L''envoûtement de la bête rend la cible répugnante aux yeux des animaux et des bêtes. Dès que la cible s’approche d’un animal à moins de 10m, ce dernier réagira mal au sujet, ce qui lui inflige un malus de -3 en survie en ce qui concerne le dressage des animaux. À chaque fois que le sujet s’approche d’un animal à moins de 10m, il y a 50% de chance pour que l’animal attaque.', 'Un petit animal vivant, 2 doses de gui, une dose de phosphore, 2 doses d''œil de corbeau, 3 doses de racine de mandragore', 'Élevé');

-- ALTER TABLE envoutement ALTER COLUMN id_envoutement RESTART WITH 7;

-- Ajout de la Magie
INSERT INTO magie (id_magie, nom, cout, effet, portee, duree, nature, niveau, contre, type) VALUES
(1, 'Compas magique', '3 END', 'Le compas magique permet de déterminer instantanément la direction vers un endroit où vous êtes déjà allée auparavant. Sinon, le sort indique le nord.', 'Personnelle', '1D6 heure', 'Mixte', 'Sort de novice', '', 'Sort'),
(2, 'Dissipation', 'Variable', 'Dissipation met fin à un sort, un rituel ou une malédiction en cours dans sa portée. Ce sort permet d’annuler une magie qui dure et peut être utilisé comme une action défensive pour bloquer une attaque magique avec ou sans composants. Pour annuler un effet magique, vous devez dépenser la moitié des points de Résilience utilisés par le lanceur et réussir un jet d’Incantation en opposition à son jet pour lancer le sort.', '10 m', 'Instantané', 'Mixte', 'Sort de novice', 'Incantation', 'Sort'),
(3, 'Glamour', '5 END', 'Glamour vous permet de mettre une illusion autour de vous qui vous fait paraître éblouissant. Ce sort vous donne un bonus de +3 en Séduction, Charisme et Commandement.', 'Personnelle', '1D6 heures', 'Mixte', 'Sort de novice', '', 'Sort'),
(4, 'Invocation de bâton', '2 END', 'Invocation de bâton vous permet de dématérialiser votre bâton et de le téléporter à un endroit où vous avez été présent au cours du dernier jour. Vous pouvez lancer à nouveau le sort pour faire revenir le bâton à vous.', '', 'Instantané', 'Mixte', 'Sort de novice', '', 'Sort'),
(5, 'Manipulation de l''esprit', '3 END', 'Manipulation de l’esprit vous permet de forcer votre cible à ressentir l’une de ces émotions pendant la durée du sort : haine, amour, dépression ou euphorie.', '5 m', '1D10 rounds', 'Mixte', 'Sort de novice', 'Résistance à la magie', 'Sort'),
(6, 'Miroir d''Afan', '3 END', 'Inventé par le talentueux magicien Aedirnien Afan de Guletta, le miroir d''Afan crée 1D10 copies illusoires du lanceur. Ces copies sont intangibles, mais impossibles à différencier du lanceur, qui les contrôle par l’esprit. Contrôler ces copies ne demande pas d’action, mais elles ne peuvent pas se déplacer au-delà de la portée du dort.', '10 m', 'Actif (2 END)', 'Mixte', 'Sort de novice', '', 'Sort'),
(7, 'Poussière aveuglante', '3 END', 'La poussière aveuglante vous permet de lancer une poussière magique dans les yeux d’une cible afin de l’aveugler pour la durée du sort.', '4 m', '1D10 rounds', 'Mixte', 'Sort de novice', 'Esquive ou Blocage', 'Sort'),
(8, 'Télépathie', '2 END', 'Télépathie vous permet de communiquer par télépathie avec une personne pendant la durée du sort, sans barrière de langage.', '10 m', 'Actif (1 END)', 'Mixte', 'Sort de novice', '', 'Sort'),
(9, 'Cenlly Graig', '3 END', 'Cenlly Graig lance des pierres acérées sur votre adversaire. Lors de votre jet, pour chaque point qui dépasse la défense de votre adversaire (maximum 10), vous infligez 1D6 points de dégâts. Chaque lancer compte comme une attaque à part entière.', '5 m', 'Instantané', 'Terre', 'Sort de novice', 'Esquive ou Blocage', 'Sort'),
(10, 'Codi Bywyd', '2 END', 'Codi Bywyd permet de faire parvenir à maturité une graine en l’espace d’un round.Cela permet de faire pousser des herbes et des plantes alchimiques, mais rien de plus grand comme un arbre.', '4 m', 'Instantané', 'Terre', 'Sort de novice', '', 'Sort'),
(11, 'Diagnostic', '3 END', 'Diagnostic permet d’évaluer rapidement la santé d’une personne et de déterminer combien de points de santé elle a, ses blessures et si elle est malade ou empoisonnée.', '5 m', 'Instantané', 'Terre', 'Sort de novice', '', 'Sort'),
(12, 'Pic terrestre', '5 END', 'Pic terrestre crée une stalagmite inclinée de manière à pouvoir poignarder une cible. Le pic inflige 5D6 points de dégâts et reste en place jusqu’à être détruit. Il peut être détruit en lui infligeant 20 points de dégâts.', '6 m', 'Instantané', 'Terre', 'Sort de novice', 'Esquive ou Blocage', 'Sort'),
(13, 'Plume de Luthien', '2 END', 'Nommé ainsi d’après son créateur, Luthien de Ebbing, Plume de Luthien peut graver des écritures ou des dessins sur n’importe quelle surface solide. Le sort ne peut pas être utilisé sur une créature vivante.', '1 m', 'Instantané', 'Terre', 'Sort de novice', '', 'Sort'),
(14, 'Prison de Talfryn', '3 END', 'Prison de Talfryn tient son nom de Talfryn de Nazair, un chevalier traître qui a été piégé trois jours durant dans le jardin du magicien Drystan. Le sort permet d’empêcher une cible dans des racines. Il faut 15 points de dégâts pour détruire les racines. Autrement, pour s’en échapper, il faut un jet d’esquive ou d’évasion avec un SD égal à votre résultat pour lancer le sort.', '10 m', 'Jusqu''à destruction', 'Terre', 'Sort de novice', 'Esquive', 'Sort'),
(15, 'Soins magiques', '5 END', 'Soins magique stimule la régénération naturelle d’une cible en lui soignant 3 points de dégâts par round. L’effet dure pendant la durée du sort. Sinon, ce sort peut être utilisé plusieurs reprises pour soigner une blessure critique.', '2 m', '1D10 rounds', 'Terre', 'Sort de novice', '', 'Sort'),
(16, 'Soufle de Korath', '2 END', 'Souffle de Korath démolit une surface de terre ou de pierre proche et pulvérise du sable brûlant dans un cône de 3m devant le lanceur. Les adversaires dans cette zone qui ratent leur défense sont aveuglés pour 1D6 rounds.', 'Cône de 3 m', 'Instantané', 'Terre', 'Sort de novice', 'Esquive ou Blocage', 'Sort'),
(17, 'Abri d''Urien', '3 END', 'Abri d''Urien, créé par le magicien de l''air Urien de Cidari, permet d''annuler les effets d''un temps hostile dans un rayon de 8 m autour du lanceur. Cela annule la chaleur et le froid extrême, la pluie et la neige.', 'Rayon de 8 m', '1D6 heures', 'Air', 'Sort de novice', '', 'Sort'),
(18, 'Adenydd', '4 END', 'Adenydd vous allège légèrement et créé une trajectoire de descente lorsque vous chutez. Ce qui signifie que pour 2 m de chute, vous avancez de 2 m dans une direction. Si vous touchez terre avant la fin du sort, vous ne subirez aucun dégâts.', 'Personnelle', 'Actif (2 END)', 'Air', 'Sort de novice', '', 'Sort'),
(19, 'Air frais', '2 END', 'Air frais dégage une zone d''un rayon de 4 m autour de vous de tout poison, fumée ou autre air vicié pendant la durée du sort.', 'Rayon de 4 m', 'Actif (2 END)', 'Air', 'Sort de novice', '', 'Sort'),
(20, 'Poche d''air', '3 END', 'Poche d''air créé une poche d''air frais sous l''eau ou dans tout autre endroit  où il n''y a normalement pas d''air respirable. La poche fait un rayon de 1 m pendant toute la durée du sort.', '12 m', '2D10 rounds', 'Air', 'Sort de novice', '', 'Sort'),
(21, 'Rafale de Bronwyn', '2 END', 'Rafale de Bronwyn tire son nom du mage et pillard skellige, Bronwyn Œil-Sûr. Le sort permet de faire reculer une cible d''autant de mettre que le nombre de points supérieurs à la défense de l''adversaire sur votre jet. Cette attaque n''inflige que 1D6 points de dégâts, mais si votre adversaire percute quelque chose, il prend des dégâts d''éperonnage.', '2 m', 'Instantané', 'Air', 'Sort de novice', 'Esquive', 'Sort'),
(22, 'Télékinésie', '3 END', 'Télékinésie permet de soulever et manipuler un objet (jusqu''à 5 ENC par niveau d''Incantation) comme si vous le teniez.', '5 m', 'Actif (2 END)', 'Air', 'Sort de novice', '', 'Sort'),
(23, 'Tempête statique', '5 END', 'Ice cream candy cotton candy soufflé ice cream toffee jelly topping. Marzipan dessert cake jelly cotton candy. Bear claw bonbon cheesecake sweet cotton candy.', 'Rayon de 5 m', '2D6 rounds', 'Air', 'Sort de novice', '', 'Sort'),
(24, 'Zéphyr', '5 END', 'Zéphyr permet de faire éclater une rafale de vent qui repousse quiconque se trouve dans un rayon de 2 m autour de vous, d''autan de mètre que le nombre de points supérieurs à sa défense sur votre jet. Cette attaque n''inflige que 1D6 points de dégâts, mais si votre adversaire percute quelque chose, il subit des dégâts d''éperonnage.', 'Rayon de 2 m', 'Instantané', 'Air', 'Sort de novice', '', 'Sort'),
(25, 'Aenye', '5 END', 'Aenye permet de lancer une boule de feu pur sur un adversaire à portée du sort. Cette boule de feu inflige 4D6 points de dégâts et à 75% de chances de mettre le feu à la cible.', '12 m', 'Instantané', 'Feu', 'Sort de novice', 'Esquive ou Blocage', 'Sort'),
(26, 'Aine Verseos', '1 END', 'Aine Verseos créé une zone de lumière vive dans un rayon de 4 m autour de vous.', '4 m', 'Actif (2 END)', 'Feu', 'Sort de novice', '', 'Sort'),
(27, 'Attiser les flammes', '3 END', 'Cotton candy cotton candy wafer ice cream jelly beans lollipop cookie brownie. Oat cake jelly-o sweet bonbon gummies cheesecake. Muffin jelly-o gummies lemon drops tart shortbread pie cotton candy. Jelly beans pie marshmallow marzipan candy.', '10 m', 'Actif (2 END)', 'Feu', 'Sort de novice', '', 'Sort'),
(28, 'Éclat magique', '2 END', 'Éclat magique créé une lumière vive au-dessus de votre tête. Quiconque se trouve dans un rayon de 8 m doit faire un jet de Résistance à la magie ou être aveuglé pendant 1D6 rounds. Cet éclat est visible à 10 Km.', '8 m', 'Instantané', 'Feu', 'Sort de novice', 'Résistance à la magie', 'Sort'),
(29, 'Marque incandescente', '4 END', 'Marque incandescente permet de marquer une cible d''un simple symbole ou mot, à n''importe quel endroit exposé de son corps. Cela inflige 1D6 points de dégâts à la cible et laisse une grande cicatrice permanente.', '8 m', 'Instantané', 'Feu', 'Sort de novice', 'Bouclier magique', 'Sort'),
(30, 'Poigne de Cadfan', '4 END', 'Poigne de Cadfan, d''après le magicien et forgeron Cadfan de Ebbing, permet de surchauffer un objet en métal, de manière à le rendre impossible à tenir en main et obligeant son porteur à le lâcher ou à subir 2D6 points de dégâts au membre qui le tient. Il est également possible de chauffer une arme pour lui octroyer un bonus de chauffer un bonus de +2D6 dégâts et 50% de chances de mettre le feu à une cible.', '8 m', '1D6 rounds', 'Feu', 'Sort de novice', '', 'Sort'),
(31, 'Tanio Ilchar', '3 END', 'Tanio Ilchar créé une explosion de feu dans une zone de 2 m sur 2 m. Il y a 100 % de chance d''enflammer une cible qui se trouve dans la zone.', '8 m', 'Instantané', 'Feu', 'Sort de novice', 'Esquive', 'Sort'),
(32, 'Vague de feu', '4 END', 'Vague de feu tire dans une direction un cône de feu de 3 m qui inflige 2D6 points de dégâts à quiconque ne peut pas esquiver ou bloquer et a 50% de chance d''enflammer une cible.', '3 m', 'Instantané', 'Feu', 'Sort de novice', 'Esquive ou Blocage', 'Sort'),
(33, 'Aire de glace', '2 END', 'Aire de glace permet de créer une zone de glace de 2 m². Quiconque traverse cette zone de glace faire une jet d’Athlétisme avec un SD égal à votre résultat d''Incantation ou déraper sur la glace.', '10 m', '2D10 rounds', 'Eau', 'Sort de novice', 'Esquive', 'Sort'),
(34, 'Averse', '2 END', 'Averse créé une zone d''un rayon de 10 m de pluie qui éteint n''importe quel feu qu''elle touche. Ce sort contrecarre les effets du feu.', '8 m', 'Actif (2 END)', 'Eau', 'Sort de novice', '', 'Sort'),
(35, 'Brouillard de Dormyn', '3 END', 'Inventé par Dormyn de Gemmery, Brouillard de Dormyn créé dans une zone d''un rayon de 10 m, centrée sur vous, un épais brouillard qui donne un malus de -3 en Vigilance à ceux qui s''y trouvent et limite la vision à 4 m.', '10 m', 'Actif (2 END)', 'Eau', 'Sort de novice', '', 'Sort'),
(36, 'Contrôle de l''eau', '5 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', 'Actif (2 END)', 'Eau', 'Sort de novice', 'SD déterminé par le MJ', 'Sort'),
(37, 'Grêle de Cary', '3 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '5 m', 'Instantané', 'Eau', 'Sort de novice', 'Esquive ou Blocage', 'Sort'),
(38, 'Malédiction de Sedna', '5 END', 'Appelé ainsi en référence aux eaux tumultueuses de l''Abysse de Sedna, considéré comme une destination suicidaire pour les bateaux, Malédiction de Sedna crée un puissant tourbillon sur une zone de 4 m. Quiconque se trouve dans les 5 m doit faire un jet de Natation ou être emporté sous l''eau. Il faut refaire un jet à chaque tour ou rester sous l''eau et commencer à suffoquer.', '12 m', 'Actif (2 END)', 'Eau', 'Sort de novice', 'Esquive', 'Sort'),
(39, 'Puro Dwr', '2 END', 'Puro Dwr permet de purifier 1m³ d''eau. Cela supprime le poison et la maladie, mais ça ne fera pas en sortir les créatures vivantes. S''il est lancé sur une petite portion d''une eau polluée, la zone visée recommencera à être polluée après la durée du sort.', '4 m', '1D10 rounds', 'Eau', 'Sort de novice', '', 'Sort'),
(40, 'Rhewi', '2 END', 'Rhewi crée une couche de glace autour d''une cible pour la durée du sort. La cible est considérée comme gelée. S''il est utilisé sur une cible non vivante, elle ne peut plus être manipulée ou déplacée.', '8 m', '1D10 rounds', 'Eau', 'Sort de novice', 'Esquive', 'Sort'),
(41, 'Illusion', '8 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '20 m', 'Actif (4 END)', 'Mixte', 'Sort de compagnon', 'Résistance à la magie', 'Sort'),
(42, 'Technique d''Eilhart', '12 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '3 m', 'Instantané', 'Mixte', 'Sort de compagnon', 'Résistance à la magie', 'Sort'),
(43, 'Téléportation', '10 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '', 'Instantané', 'Mixte', 'Sort de compagnon', '', 'Sort'),
(44, 'Rhwystr Graig', '15 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '20 m', 'Jusqu''à destruction', 'Terre', 'Sort de compagnon', '', 'Sort'),
(45, 'Séisme de Stammelford', '12 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '30 m', '1D10 rounds', 'Terre', 'Sort de compagnon', 'Esquive', 'Sort'),
(46, 'Théorie d''Elgan', '10 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '8 m', '2D10 rounds', 'Terre', 'Sort de compagnon', '', 'Sort'),
(47, 'Gwynt Troelli', '12 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', 'Rayon de 10 m', 'Actif (4 END)', 'Air', 'Sort de compagnon', '', 'Sort'),
(48, 'Suffocation', '14 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', 'Actif (4 END)', 'Air', 'Sort de compagnon', 'Résistance à la magie', 'Sort'),
(49, 'Tonnerre d''Alzur', '15 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '25 m', 'Instantané', 'Air', 'Sort de compagnon', 'Esquive', 'Sort'),
(50, 'Afflux de Demetia', '12 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', 'Actif (4 END)', 'Feu', 'Sort de compagnon', '', 'Sort'),
(51, 'Prise de Seirff', '10 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', '2D10 rounds', 'Feu', 'Sort de compagnon', 'Esquive', 'Sort'),
(52, 'Vortex enflammé', '15 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', 'Actif (4 END)', 'Feu', 'Sort de compagnon', 'Esquive', 'Sort'),
(53, 'Anialwch', '8 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', 'Instantané', 'Eau', 'Sort de compagnon', 'Résistance à la magie', 'Sort'),
(54, 'Grêle dévastatrice de Merigold', '15 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '30 m', 'Actif (4 END)', 'Eau', 'Sort de compagnon', 'Esquive', 'Sort'),
(55, 'Vague de Naglfar', '10 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', 'Rayon de 3 m', 'Instantané', 'Eau', 'Sort de compagnon', 'Esquive ou Blocage', 'Sort'),
(56, 'Commandement psychique', '25 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', 'Jusqu''à la fin de la tâche', 'Mixte', 'Sort de maître', 'Résistance à la magie', 'Sort'),
(57, 'Portail', '22 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '10 m', 'Actif (6 END)', 'Mixte', 'Sort de maître', '', 'Sort'),
(58, 'Polymorphisme', '22 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', 'Personnelle', 'Jusqu''au nouveau lancement du sort', 'Terre', 'Sort de maître', '', 'Sort'),
(59, 'Transmutation', '25 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '2 m', 'Permanent', 'Terre', 'Sort de maître', '', 'Sort'),
(60, 'Derviche', '22 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', 'Rayon de 2 m', 'Actif (6 END)', 'Air', 'Sort de maître', 'Esquive', 'Sort'),
(61, 'Orage', '25 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '20 m', 'Actif (6 END)', 'Air', 'Sort de maître', 'Esquive', 'Sort'),
(62, 'Effet mirroir', '25 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '20 m', '2D6 rounds', 'Feu', 'Sort de maître', 'Esquive ou Blocage', 'Sort'),
(63, 'Feu de Melgar', '25 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', 'Rayon de 40 m', '2D6 rounds', 'Feu', 'Sort de maître', 'Esquive ou Blocage', 'Sort'),
(64, 'Séparation des eaux', '25 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', 'Rayon de 10 m', 'Actif (6 END)', 'Eau', 'Sort de maître', '', 'Sort'),
(65, 'Tryferi Gaeaf', '22 END', 'Donut gummies chocolate topping brownie apple pie. Chupa chups wafer biscuit marshmallow dessert macaroon chocolate bear claw. Fruitcake jelly-o apple pie bonbon macaroon sweet roll ice cream lemon drops chupa chups.', '20 m', '1D10 rounds', 'Eau', 'Sort de maître', 'Esquive ou Blocage', 'Sort'),
(66, 'Yrden', 'Variable', 'Yrden dessin au sol autour de vous un grand cercle magique. Tout ce qui entre dans le cercle subit un malusà la VIT et au RÉF.', 'rayon de 3 m', '5 round', 'Mixte', 'Signe de base', '', 'Signe'),
(67, 'Aard', 'Variable', 'Aard déclenche une vague de force télékinésique qui stupéfie les créatures avec 10% de chance pour chaque point d''END dépensé.', 'Cône de 2 m', 'instantané', 'Air', 'Signe de base', 'Esquive', 'Signe'),
(68, 'Quen', 'Variable', 'Quen crée un bouclier avec 5 points de santé par points d''END dépensé. Si vous échouez à vous défendre (ou que vous ne voulez/pouvez pas vous défendre) contre une attaque ou un effet infligeant des dégâts, ces dégâts sont infligés en priorité au bouclier Quen. Les dégâts létaux et non létaux réduisent d''autant les points de santé du bouclier. Si le bouclier Quen est réduit à 0 point de santé, les dégâts surnuméraires vous sont infligés et doivent pénétrer votre armure et votre éventuelle résistance aux dégâts afin d''impacter vos points de santés ou votre Endurance. Quen peut être utilisé pour se défendre contre les sorts pouvant être bloqués, mais est inefficace dans le cas contraire. Le signe ne protège pas non plus des dégâts infligés par un poison déjà absorbé/inoculé, une maladie ou la suffocation. Vous ne pouvez pas relancer à nouveau Quen tant que ses points de santé n''ont pas été épuisés ou qu''il ne s''achève (10 rounds).', 'personnelle', '10 rounds ou jusqu''à épuisement', 'Terre', 'Signe de base', '', 'Signe'),
(71, 'Contrôle de l''eau', '5 END', 'Contrôle de l''eau permet de contrôler la vitesse à laquelle un plan d''eau bouge et dans quelle direction il va pendant la durée du sort. On peut l''utiliser pour ralentir de moitié une cible qui nage, réduire de moitié la vitesse d''un navire ou ralentir ou arrêter le courant d''une rivière.', '10 m', 'Actif (2 END)', 'Eau', 'Sort de novice', '', 'Sort'),
(72, 'Grêle de Cary', '3 END', 'Nommé ainsi d''après son créateur, Carys de Cintra, ce sort projette des plombs de glace à très haute vitesse sur un adversaire. Pour chaque point que vous obtenez au-dessus de l''Esquive ou du Blocage de votre adversaire (maximum 5), vous infligez 1D6 points de dégâts et avez 25 % de chances de geler votre opposant. Chaque jet est une attaque unique pour déterminer les dégâts et leur localisation.', '5 m', 'instantané', 'Eau', 'Sort de novice', '', 'Sort'),
(74, 'Ami des espèces sauvage', '1 END', 'Ami des espèces sauvages octroie au lanceur un bonus de +3 en Survie pour dresser des animaux. L''invocation peut aussi apaiser un animal si le jet d''Incantation dépasse la VOL x 3 de l''animal.', 'Personelle ou 5 m', '1D6 heures', 'Aucun', 'Invocation novice de druide', 'Volonté de la créature x3', 'Invocation'),
(75, 'Don ce la nature', 'Variable', 'Don de la nature fait pousser une petite grappe de plantes comestibles dans n''importe quel sol. Ces plantes sont suffisantes pour nourrir autant de personnes pendant un jour que le nombre de points d''END dépensés.', '2 m', 'instantané', 'Aucun', 'Invocation novice de druide', NULL, 'Invocation'),
(76, 'Emblème de l''invisible', '2 END', 'En dessinant l''Emblème de l''invisible, vous couvrez une zone  de 3 m avec des branches, des feuillages et autres éléments naturels afin d''obtenir une couverture visuelle totale. Cela vous octroie un bonus de +5 à la Discrétion, mais immobilise ceux qui se trouvent dans la zone et l''invocation doit être relancée pour se découvrir. Vous pouvez tailler à travers les broussailles en leur infligeant 10 points de dégâts.', 'personnelle', 'jusqu''à dissipation', 'Aucun', 'Invocation novice de druide', NULL, 'Invocation'),
(77, 'Maladiction', 'Variable', 'Maladiction rend une cible malade. La maladie se manifeste différemment, selon comment les points de Résilience sont dépensés. Avec 2 points, la cible est pliée en deux parla toux et stupéfiée. Avec  4 points, la cible est gravement malade et étourdie.', '8 m', 'le jet de Résilence y met fin', 'Aucun', 'Invocation novice de druide', 'Résistance à la magie', 'Invocation'),
(78, 'Sang bouillonnant', '3 END', 'Sang bouillonnant provoque la rage chez un animal ou un monstre non sensible à l''encontre d''une cible. La créature attaquera la cible choisie jusqu''à la fin du sort.', '8 m', '1D10 rounds', 'Aucun', 'Invocation novice de druide', 'Volonté de la créature x3', 'Invocation'),
(79, 'Vision naturelle', '2 END', 'Vision naturelle permet de voir les créatures qui ne sont pas de ce royaume. Cela vous permet de voir les monstres à 50 m, même à travers les obstacles. Les monstres ainsi repérés apparaissent sous une version lumineuse d''eux même.', 'personelle', 'actif (1 END)', 'Aucun', 'Invocation novice de druide', NULL, 'Invocation'),
(80, 'Igni', 'Variable', 'Igni projette une vague d''étincelles et de feu qui inflige 1D6 points de dégâts par point d''END dépensé et à 50% de chance de mettre le feu à tout ce qu''elle touche. Igni inflige toujours ses dégâts au torse, à moins qu''il ne soit utilisé à bout portant. Lorsqu''Igni est utilisé à bout portant, peut prendre pour cible n''importe localisation.', 'Cône de 2 m', 'instantané', 'Feu', 'Signe de base', 'Esquive', 'Signe'),
(81, 'Axii', 'Variable', 'Axii étourdit un adversaire jusqu''à ce qu''il réussisse une jet de sauvegarde contre l''étourdissement avec un malus de -1. pour 2 points d''END supplémentaires dépensés, le jet de sauvegarde contre l''étourdissement est plus difficile de 1 point.', '8 m', 'jusqu''à s''en débarasser', 'Eau', 'Signe de base', '', 'Signe');

-- Ajout des Rituels
INSERT INTO rituel (id_rituel, nom, cout, effet, temps_preparation, sd, duree, composant, niveau)VALUES
(1, 'Rituel de magie', '3 END', 'Le Rituel de magie crée un cercle magique qui renforce la tolérance à la magie, en accordant un bonus au seuil de Vigueur égal à la moitié du niveau de Rituels du lanceur. Ce bénéfice est accordé à la première personne avec des capacité magique qui pénètre dans le cercle et se concentre dessus, et dure 5 heures. Autrement, le lanceur peut dépenser le cercle pour gagner 1D6/2 unités de cinquième essence.', '5 rounds', '15', 'une utilisation', '1 poussière imprégnée, 2 craies, 2 dose de soufre, 2 verres', 'Rituel de novice'),
(2, 'Hydromencie', '5 END', 'Hrydromencie permet de fixer une petite flaque d''eau pour y apercevoir un évènement  qui c''est passé au cours des deux derniers jours ou a lieu au moment même. Regarder un évènement du passé se fait sur le SD de base. Si vous essayez de voir un évènement qui se passe au moment même, augmentez le SDde 3. Si vous observez un évènement présent, si un magicien y est présent, il peut sentir l''augure avec un jet d''Exercice de la magie supérieur à votre jet de Rituels.', '5 rounds', '15 (18)', 'actif (2END)', 'une petite quantité d''eau ou un bol d''eau, 1 éclat de lune, 1 fruit de berbéris, 2 dose de cinquième essence, 2 perles, 2 pétales de myrte blanc.', 'Rituel de novice'),
(3, 'Pyromancie', '3 END', 'Pyromancie permet de fixer un feu et y observer des évènements qui se passent au même moment. Pyromancie est plus dangereux qu''Hydromancie, ce qui le rend plus difficile à maintenir et impossible à regarder à l''envers. Cependant, il es plus facile de voir des évènements présents. Tout comme avec Hydromencie, un mage que vous observez ainsi peut sentir l''augure avec un jet d''Exercice de la magie supérieur a votre jet de Rituels.', '5 rounds', '15', 'actif (4END)', 'un petit feu, 2 dose de cinquième essence, 2 dose de cendres, 2 dose de cire, 2 œils de corbeau, 5 calcium equun', 'Rituel de novice'),
(4, 'Message magique', '3 END', 'Message magique permet d''enregistrer un message de 5 minutes dans une gemme ou un bout de verre gravé d''un emblème magique. Vous pouvez déterminer jusqu''à trois déclencheurs spécifiques qui activeront le message. Une fois lu, le message reste en dormance jusqu''au prochain déclencheur. Quand il est déclenché, une illusion du lanceur apparaît et délivre le message. S''il est enregistré dans une gemme parfaite, le message est aussi clair que si le ritualiste était physiquement présent.', '5 rounds', '12', 'permanent', '1 dose de cinquième essence, 1 solution de mercure, 1 verre', 'Rituel de novice'),
(5, 'Rituel de purification', '3 END', 'Rituel de purification purifie le corps d''une cible de tout poison ou maladie. Quand il est activé, le lanceur fait un jet de Rituels contre un SD spécifique afin de nettoyer le corps de la cible. L''alcool et les drogues sont assez facile, avec un SD 12. Les poisons et les huiles sont plus difficiles, avec un SD 15. Les maladies graves sont très difficiles à purifier avec un SD 18. Rituel purificateur ne permet pas de soigner les épidémies telles que la catriona.', '5 rounds', 'variabl', 'instantané', '1 feuille de balisse, 1 liqueur, 1 œil de corbeau, 2 craies, 2 dose de gui', 'Rituel de novice');

-- ALTER TABLE rituel ALTER COLUMN id_rituel RESTART WITH 11;

-- Ajout des Races
INSERT INTO race (id_race, nom) VALUES
    (1, 'Humain'),
    (2, 'Nain'),
    (3, 'Elfe'),
    (4, 'Halfelin'),
    (5, 'Sorceleur');

-- ALTER TABLE race ALTER COLUMN id_race RESTART WITH 6;

-- Ajout des particularités
INSERT INTO particularite (id_particularite, nom, description, id_race) VALUES
(1, 'Sens accrus', 'Les sorceleurs ont des sens plus développés que la moyenne des humains.', 5),
(2, 'Mutation durable', 'Les sorceleurs ont subi des mutations qui les rendent différents des autres humains.', 5),
(3, 'Sensibilité émoussée', 'Les sorceleurs ont une sensibilité émoussée par rapport aux autres humains.', 5),
(4, 'Réflexes hors du commun', 'Les sorceleurs ont des réflexes hors du commun.', 5),

(5, 'Esthète', 'Les elfes sont des êtres sensibles à la création artistique.', 3),
(6, 'Oeil d''aigle', 'Les elfes ont une vue perçante.', 3),
(7, 'Harmonie avec la nature', 'Les elfes ont une affinité particulière avec la nature.', 3),

(8, 'Tanné comme le cuir', 'Les nains sont réputés pour leur résistance physique.', 2),
(9, 'Coriace', 'Les nains sont coriace.', 2),
(10, 'Oeil de l''expert', 'Les nains repèrent facilement les petits détails.', 2),

(11, 'Digne de confiance', 'Les humains sont réputés pour leur confiance.', 1),
(12, 'Ingénieux', 'Les humains sont ingénieux.', 1),
(13, 'Têtu comme une mule', 'Les humains sont têtu comme des mules.', 1),

(14, 'Agile', 'Les halfelins sont agiles.', 4),
(15, 'Peuple agreste', 'Les halfelins sont des peuples agrestes.', 4),
(16, 'Résilience à la magie', 'Les halfelins sont résilients à la magie.', 4);

-- ALTER TABLE particularite ALTER COLUMN id_particularite RESTART WITH 17;

-- Ajout des réputations
INSERT INTO reputation_wiki (id_reputation_wiki, territoire, valeur, id_race) VALUES
(1, 'Nord', 'Craint et haïs', 5),
(2, 'Nilfgaard', 'Craint et haïs', 5),
(3, 'Skellige', 'Toléré', 5),
(4, 'Dol Blathana', 'Toléré', 5),
(5, 'Mahakam', 'Toléré', 5),

(6, 'Nord', 'Haïs', 3),
(7, 'Nilfgaard', 'Neutre', 3),
(8, 'Skellige', 'Neutre', 3),
(9, 'Dol Blathana', 'Neutre', 3),
(10, 'Mahakam', 'Neutre', 3),

(11, 'Nord', 'Toléré', 2),
(12, 'Nilfgaard', 'Neutre', 2),
(13, 'Skellige', 'Neutre', 2),
(14, 'Dol Blathana', 'Neutre', 2),
(15, 'Mahakam', 'Neutre', 2),

(17, 'Nilfgaard', 'Neutre', 1),
(18, 'Skellige', 'Neutre', 1),
(19, 'Dol Blathana', 'Haïs', 1),
(20, 'Mahakam', 'Tolérés', 1),

(21, 'Nord', 'Toléré', 4),
(22, 'Nilfgaard', 'Neutre', 4),
(23, 'Skellige', 'Neutre', 4),
(24, 'Dol Blathana', 'Neutre', 4),
(25, 'Mahakam', 'Neutre', 4);

-- ALTER TABLE particularite ALTER COLUMN id_reputation_wiki RESTART WITH 26;
